### ISSUE TITLE
Need help to create own pool by ckpool platform.

### ISSUE THREAD

**Issue by AndreyNag** [ctubio/ckpool#1]
Hi everybody.
I'm seraching stratum pool for my own pool for peercoin. Is it posible on ckpool? If it`s posible help me please find any information to create one. Documentation on the official website very poor. Only keys for command prompt. It's not enough.
Thanks.

**Comment by ctubio** [comment]
Hello AndreyNag,
feel free to make this question at the official ckpool forum https://bitcointalk.org/index.php?topic=789369.0

my answer is yes, because peercoin and bitcoin use the same algo, and ckpool works great with bitcoin; but i may be missing something so please better ask directly to the author of ckpool for any limitations with altcoins.

About the documentation, it should be enough, it even should be enough just with the source code, the documentation in place is a gift; otherwise if you still miss something please detail what exact question are you having, here or in the official ckpool forum.
